### Base URL
@host=http://localhost:8081/api/v1/books

############################################################
### Create Book
############################################################
POST {{host}}
Content-Type: application/json

{
  "title": "Clean Architecture",
  "author": "Robert C. Martin",
  "isbn": "9780134494166",
  "publishedYear": 2017,
  "price": 52.00
}

###

############################################################
### Get All Books
############################################################
GET {{host}}

###

############################################################
### Get Book By Id
############################################################
GET {{host}}/1

###

############################################################
### Search Books By Author
############################################################
GET {{host}}/search?author=Martin

###

############################################################
### Search Books By Author (Craig)
############################################################
GET {{host}}/search?author=Craig

###

############################################################
### Update Book
############################################################
PUT {{host}}/1
Content-Type: application/json

{
  "title": "Spring Boot 3.5",
  "author": "Craig Walls",
  "isbn": "9781617292545",
  "publishedYear": 2026,
  "price": 59.99
}

###

############################################################
### Delete Book
############################################################
DELETE {{host}}/10

###

############################################################
### Create Another Book
############################################################
POST {{host}}
Content-Type: application/json

{
  "title": "Learning Spring AI",
  "author": "Manivannan",
  "isbn": "9789876543210",
  "publishedYear": 2026,
  "price": 39.99
}

###

############################################################
### Invalid Request - Validation Test
############################################################
POST {{host}}
Content-Type: application/json

{
  "title": "",
  "author": "",
  "isbn": "123",
  "publishedYear": 1000,
  "price": -20
}

###

############################################################
### Book Not Found
############################################################
GET {{host}}/9999

###

############################################################
### Update Non Existing Book
############################################################
PUT {{host}}/9999
Content-Type: application/json

{
  "title": "Unknown",
  "author": "Unknown",
  "isbn": "9781231231231",
  "publishedYear": 2026,
  "price": 25.00
}

###

############################################################
### Delete Non Existing Book
############################################################
DELETE {{host}}/9999